changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 💥 Breaking Changes
      labels:
        - 'breaking-change'
    - title: 🎉 New Features
      labels:
        - 'new-feature'
    - title: 🐞 Bug Fixes
      labels:
        - 'bug-fix'
    - title: 🚀 Performance Improvements
      labels:
        - performance
    - title: 🔧 Engineering
      labels:
        - 'engineering'
        - 'refactoring'
    - title: 🎨 Rendering
      labels:
        - rendering
    - title: ✨ Enhancement
      labels:
        - 'enhancement'
    - title: 📄 Docs
      labels:
        - documentation
    - title: 🎓 Examples
      labels:
        - 'example'
    - title: 🔁 Build & Deploy
      labels:
        - 'ci-cd'
    - title: 💪 Other Changes
      labels:
        - "*"
