name: .NET Build and Publish Nuget

env:
  PROJECT_PATH: src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Stride Community Toolkit
      uses: actions/checkout@v3

    - name: .NET Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore

    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} --no-build --verbosity normal

    - name: Publish Stride Community Toolkit
      uses: alirezanet/publish-nuget@v3.0.1
      with:
        PROJECT_FILE_PATH: ${{ env.PROJECT_PATH }}
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
