name: .NET Build Test

env:
  PROJECT_PATH_CORE: src\Stride.CommunityToolkit\Stride.CommunityToolkit.csproj
  PROJECT_PATH_SKYBOX: src\Stride.CommunityToolkit.Skyboxes\Stride.CommunityToolkit.Skyboxes.csproj

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Stride Community Toolkit
      uses: actions/checkout@v4

    - name: .NET Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Stride.CommunityToolkit dependencies
      run: dotnet restore ${{ env.PROJECT_PATH_CORE }}

    - name: Build Stride.CommunityToolkit
      run: dotnet build ${{ env.PROJECT_PATH_CORE }} --no-restore

    - name: Test Stride.CommunityToolkit
      run: dotnet test ${{ env.PROJECT_PATH_CORE }} --no-build --verbosity normal

    - name: Restore Stride.CommunityToolkit.Skyboxes dependencies
      run: dotnet restore ${{ env.PROJECT_PATH_SKYBOX }}

    - name: Build Stride.CommunityToolkit.Skyboxes
      run: dotnet build ${{ env.PROJECT_PATH_SKYBOX }} --no-restore
