name: .NET Build Test

env:
  PROJECT_PATH: src\Stride.CommunityToolkit\Stride.CommunityToolkit.csproj

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Stride Community Toolkit
      uses: actions/checkout@v4

    - name: .NET Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore

    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} --no-build --verbosity normal
