name: Build Stride Community Toolkit Docs - GitHub Pages
on:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - 'README.md'
  #     - 'BuildDocs.ps1'
  #     - 'wiki/**'
  #     - '.github/**'
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: windows-2022
    steps:
    #- name: Display .NET Core information
    #  run: dotnet --info

    - name: Dotnet Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Checkout Stride Community Toolkit
      uses: actions/checkout@v4

    - run: dotnet tool update -g docfx
#    - run: dotnet tool install -g docfx --version 2.65.1

    - name: Build documentation
      run: docfx docfx.json
      working-directory: docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site